app.controller('ColorPicker', function($scope, $stateParams){
	$scope.colors = [
		{name: 'grey',
		 hex: '9e9e9e'},
		{name: 'white',
	 	 hex: 'FFFFFF'},
	 	{name: 'red',
	 	 hex: 'ff5252'},
	 	{name: 'orange',
	 	 hex: 'ffa726'},
	 	{name: 'yellow',
	 	 hex: 'ffd600'},
	 	{name: 'green',
	 	 hex: '81c784'},
	 	{name: 'blue',
	 	 hex: 'bbdefb'},
	 	{name: 'purple',
	 	 hex: 'b39ddb'},
	 	{name: 'pink',
	 	 hex: 'f48fb1'},
	 	{name: 'indigo',
	 	 hex: '9fa8da'},
	 	{name: 'teal',
	 	 hex: '80cbc4'},
	 	{name: 'cyan',
	 	 hex: '4dd0e1'},
	 	{name: 'lime',
	 	 hex: '9ccc65'},
	 	{name: 'red-orange',
	 	 hex: 'ff7043'},
	 	{name: 'blue-grey',
	 	 hex: 'b0bec5'}
	];

});